### ISSUE TITLE
CICD Bugs

### ISSUE THREAD

**Issue by msampathkumar** [terraform-google-modules/terraform-docs-samples#518]
### TL;DR

PTAL https://github.com/terraform-google-modules/terraform-docs-samples/pull/510#issuecomment-1773460542

CICD is failing for unrelated errors. 

### Terraform Configuration

```hcl
NA
```

### Terraform Version

```sh
NA
```

**Comment by rogerthatdev** [comment]
The root of the problem is this error that occurs on the first step of the build config:
```
fatal: ambiguous argument 'origin/': unknown revision or path not in the working tree.
```



This is due to [this line](https://github.com/terraform-google-modules/terraform-docs-samples/blob/3a70ce38a53fa7bea0704ddca60c400e2ddbde22/build/int.cloudbuild.yaml#L24) in the yaml config that uses `git diff origin/${_BASE_BRANCH} --name-only > _changed_files` to make a list of files that the PR updates.  

The problem seems to be that for some PRs such as this one that are coming from a fork, `_BASE_BRANCH` does not evaluate to `main`.

**Comment by rogerthatdev** [comment]
I'll add that it's possible for tests to pass instead of fail with this issue because the tests continue as if there are no files changed in the PR ([example](https://console.cloud.google.com/cloud-build/builds/9afae676-292c-4723-8e8a-5a3ce8004164?project=2843445864) where the test passes but it does not run the changed terraform) 

In the meantime, it will be important to verify that the int tests are passing for the impacted samples of each PR reviewed.

**Comment by glasnt** [comment]
re: enforcing failure:  Cloud Build steps that finish with an exit code != 0 fail the entire build, but not when it happens within the step itself (like bash). Adding a `set -e` will exit the step with failure on first failure (as long as the `fatal` in git returns the appropriate exit code), causing the whole build to fail. 

re: missing substitution variable: I'll investigate further.

**Comment by glasnt** [comment]
Reproduction in https://github.com/glasnt/cloud-build-context/pull/3/checks?check_run_id=20515490284

_BASE_BRANCH had value in the fork, but in case it didn't, adding the `set -e` should ensure failures actually fail out the build. 

Updated https://github.com/terraform-google-modules/terraform-docs-samples/pull/528 to add `-e`

**Comment by glasnt** [comment]
@msampathkumar #608 should resolve this issue, ptal
